# -*- coding: utf-8 -*-
{
    'name': "Conexion a3ERP con Odoo",
    'summary': "Modulo para la sincronización de Clientes/Contactos, Productos, Tarifas y Pedidos entre a3ERP y Odoo.",
    'description': """
        Modulo para la sincronización de Clientes/Contactos, Productos, Tarifas y Pedidos, y demás tablas complementarias entre a3ERP y Odoo mediante el web service de a3ERP.
    """,
    "license": "AGPL-3",
    'author': "Tecniloop",
    'website': "https://www.tecniloop.es",
    "maintainers": ["enrjuli"],
    "category": "Extra Tools",
    'version': '19.0.4.1.1', 
    'depends': [ 
        'base','base_automation','purchase',
        'crm','sale_management',
        'sale_crm','contacts',
        'account_payment_mode',
        'tl_products_obligatorios',
        'partner_contact_address_default',
        'l10n_es_partner',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        "data/analytic_account_data.xml",
        "data/error_email_template.xml",
        'views/a3erp/a3erp_views.xml',
        'views/a3erp/a3erp_clientes_views.xml',
        'views/a3erp/a3erp_contactos_views.xml',
        'views/a3erp/a3erp_productos_views.xml',        
        'views/a3erp/a3erp_idioma_views.xml',        
        'views/a3erp/a3erp_campos_views.xml',
        'views/a3erp/a3erp_logs_views.xml',    
        # 'views/a3erp/a3erp_tarifas_views.xml',
        # 'views/a3erp/a3erp_precios_esp_views.xml',
        # 'views/a3erp/a3erp_descuentos_ac_views.xml',
        # 'views/a3erp/a3erp_descuentos_fam_views.xml',
        # 'views/a3erp/a3erp_descuentos_ff_views.xml',
        'views/a3erp/a3erp_caracteristicas_views.xml',
        'views/a3erp/a3erp_dirent_views.xml',
        'views/a3erp/a3erp_extra_views.xml',
        'views/a3erp/a3erp_proveed_views.xml',
        'views/a3erp/a3erp_familias_views.xml',
        'views/a3erp/a3erp_botones_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',       
        'views/purchase_order_views.xml',
        'views/res_users_views.xml',       
        'views/base_views.xml',   
        'views/product_template_view.xml',   
        'views/res_caracteristicas_views.xml',   
        'views/res_cargos_views.xml',   
        'views/res_company_views.xml',   
        'views/product_supplierinfo_views.xml',   
        'wizard/confirmation_wizard_view.xml',   
        'wizard/product_stock_wizard_views.xml',
        'wizard/create_date_wizard_views.xml',
        'wizard/send_confirmation_wizard.xml',
    ],        
    
    'post_init_hook': 'post_init_insert_a3erp_required_fields',
    'auto_install': False,
}

