{
    "name": "TL BC3 Budget",
    "summary": "Presupuestos técnicos BC3 con capítulos, partidas y mediciones",
    "version": "19.0.1.2.3",
    "category": "Construction/BC3",
    "author": "Tecniloop",
    "website": "https://www.tecniloop.com",
    "license": "AGPL-3",
    "depends": ["tl_bc3_base"],
    "data": [
        "security/ir.model.access.csv",
        "views/bc3_budget_views.xml",
        "views/bc3_budget_line_views.xml",
        "views/bc3_file_views.xml",
        "views/bc3_menu_views.xml",
        "reports/bc3_budget_report.xml",
        "reports/bc3_budget_templates.xml",
    ],
    "installable": True,
}
