{
    "name": "TL BC3 Product",
    "summary": "Import BC3/FIEBDC catalog concepts as eCommerce products",
    "version": "19.0.1.0.0",
    "category": "Construction/BC3",
    "author": "Tecniloop",
    "website": "https://www.tecniloop.com",
    "license": "AGPL-3",
    "depends": ["tl_bc3_base", "product", "website_sale", "brand"],
    "data": [
        "security/ir.model.access.csv",
        "views/product_template_views.xml",
        "views/bc3_concept_views.xml",
        "views/bc3_file_views.xml",
        "views/bc3_product_import_views.xml",
        "views/bc3_menu_views.xml",
        "wizards/bc3_product_import_wizard_views.xml",
    ],
    "installable": True,
}
